### ISSUE TITLE
Check for reverse paths in a more efficient way

### ISSUE THREAD

**Issue by joaorodr84** [joaorodr84/tpp#1]
Entre duas strings de permutações de caracteres distintos, como é o caso, basta comparar o primeiro com o último caracter, considerando apenas as strings em que o primeiro caracter é mais baixo que o último caracter. Portanto, é suficiente para saber se o trajeto está duplicado, saber se o número do primeiro mercado é menor que o número do último mercado. Num estado em que apenas existem por colocar mercados com número inferior ao primeiro mercado, podem-se excluir todos, já que a situação anterior irá ser sempre verificada (caso do nó C, no exemplo, faltam colocar B e A, ambos com número mais baixo, pelo que apenas podem ser geradas permutações duplicadas).
JC

**Comment by jcoelho72** [comment]
You do not need to compare nothing stored, just throw out the paths that first city have a index number greater than the last city.

**Comment by joaorodr84** [comment]
It seems we have a simple and effective solution. :) Thanks a lot.

/* Checks whether the path is reverse, i.e. whether the first market has a ID greater that the last market */
bool TPP::isReversePath() {
    return this->path.front() > this->path.back();
}


BEFORE using isReverse()

1  12  123
   13  132
2 (21) 213
   23  (231)
3 (31) (312)
  (32) (321)

--> 15 solutions (the reverse solutions are between parentesis)


AFTER using isReverse()

1  12  123
   13  132
2      213
   23
3

--> 9 solutions


-----

RESULTS

Markets			3	7		8		9		10		11
with reverse	0s	0.04s	0.23s	2.05s	34.57s	557.37s
without reverse	0s	0.02	0.20s	1.50s	18.82s	449.51s
